In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [188]:
from IPython import get_ipython
py = get_ipython()
if py is not None:
    ipy.run_line_magic('matplotlib', 'qt5')

## Gaussian Beam Intensity

$$ \large I(\rho , z) = I_0 \ (\frac{\omega_{0}}{\omega(z)}) ^2 \; \exp {(\frac{-2\rho^2}{\omega^{2}(z)})} $$ 

$$ \omega(z) = \omega_0 \ \large [1 + (\frac{z}{z_R})^2]^{\frac{1}{2}}  $$

$$ \large z_R = \frac{\pi \ \omega_0^2}{\lambda} $$

$$ \large \theta = \frac{\lambda}{\pi \ \omega_0} \ \ \ \ \ \ \ \ \ \ \ for \ z >> z_R$$

In [190]:
# measured values                        (squared Voltage)
z = 1
wl = 714.285 * 1e-6              # (m) wavelength
angle = 1.8 * (np.pi/180)              # (radian) divergence angle of the beam     
w_0 = wl / (np.pi* angle)
z_r = (np.pi* w_0**2)/ wl

In [191]:
I_o = 0.00538756 
w_z = w_0 * np.sqrt(1+(z/z_r))

In [157]:
plt.figure(figsize=(15,10))
w_z = w_0 * np.sqrt(1+(z/z_r))
x= np.linspace(-w_z,w_z,1001)
y= np.linspace(-w_z,w_z,1001)
xv, yv = np.meshgrid(x,y)
r = np.sqrt(xv**2+yv**2)
I = I_0 * (w_0/w_z)**2 * np.exp(-2*r**2/(w_z**2))
plt.pcolormesh(xv,yv,I,shading= 'auto')
plt.colorbar()

# Experimental data

In [158]:
names=['phi', 'theta', 'V']
df = pd.read_csv('data1.csv', header=None, delimiter = ';',names=names, index_col= False)
df['sq_V'] = df['V']**2

In [159]:
data = df[df['theta']<2]
data.head()

phi  theta       V      sq_V
41  0.0    1.8  0.0246  0.000605
42  0.0    1.6  0.0313  0.000980
43  0.0    1.4  0.0383  0.001467
44  0.0    1.2  0.0458  0.002098
45  0.0    1.0  0.0533  0.002841

In [160]:
print(data.sq_V.max())
print(data.sq_V.min())

0.005387560000000001
0.00047524


In [161]:
phi = np.arange(0,360,5)
theta = np.linspace (1.8,0,10)

In [162]:
theta, phi = np.meshgrid(theta,phi)

In [163]:
phi

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   5,   5,   5,   5,   5,   5,   5,   5,   5],
       [ 10,  10,  10,  10,  10,  10,  10,  10,  10,  10],
       [ 15,  15,  15,  15,  15,  15,  15,  15,  15,  15],
       [ 20,  20,  20,  20,  20,  20,  20,  20,  20,  20],
       [ 25,  25,  25,  25,  25,  25,  25,  25,  25,  25],
       [ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30],
       [ 35,  35,  35,  35,  35,  35,  35,  35,  35,  35],
       [ 40,  40,  40,  40,  40,  40,  40,  40,  40,  40],
       [ 45,  45,  45,  45,  45,  45,  45,  45,  45,  45],
       [ 50,  50,  50,  50,  50,  50,  50,  50,  50,  50],
       [ 55,  55,  55,  55,  55,  55,  55,  55,  55,  55],
       [ 60,  60,  60,  60,  60,  60,  60,  60,  60,  60],
       [ 65,  65,  65,  65,  65,  65,  65,  65,  65,  65],
       [ 70,  70,  70,  70,  70,  70,  70,  70,  70,  70],
       [ 75,  75,  75,  75,  75,  75,  75,  75,  75,  75],
       [ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80

In [164]:
phi_rad = phi * (np.pi/180)


In [165]:
theta

array([[1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. ],
       [1.8, 1.6, 1.4, 1.2, 1. , 0.8, 0.6, 0.4, 0.2, 0. 

In [166]:
theta_rad = theta*(np.pi/180)

In [167]:
values= data.sq_V.values          #data values of sq_V
values

array([0.00060516, 0.00097969, 0.00146689, 0.00209764, 0.00284089,
       0.00354025, 0.004225  , 0.00478864, 0.005184  , 0.00535824,
       0.00059049, 0.00097344, 0.00147456, 0.00210681, 0.00285156,
       0.00355216, 0.00423801, 0.00480249, 0.00519841, 0.00535824,
       0.00061504, 0.00098596, 0.00151321, 0.00215296, 0.00288369,
       0.00357604, 0.00427716, 0.00481636, 0.00521284, 0.00538756,
       0.00062001, 0.00101124, 0.00154449, 0.002209  , 0.00292681,
       0.00361201, 0.00430336, 0.00483025, 0.00524176, 0.00537289,
       0.00065025, 0.00104329, 0.00157609, 0.00226576, 0.00298116,
       0.00366025, 0.00432964, 0.00484416, 0.00522729, 0.00537289,
       0.00069169, 0.00109561, 0.00163216, 0.00231361, 0.00304704,
       0.00373321, 0.004356  , 0.00487204, 0.00529984, 0.00537289,
       0.00073984, 0.001156  , 0.00168921, 0.00238144, 0.00310249,
       0.00379456, 0.00440896, 0.0049    , 0.00525625, 0.00535824,
       0.00078961, 0.00121801, 0.00177241, 0.00245025, 0.00315

In [168]:
squared_voltage = values.reshape(72,10)

In [169]:
squared_voltage

array([[0.00060516, 0.00097969, 0.00146689, 0.00209764, 0.00284089,
        0.00354025, 0.004225  , 0.00478864, 0.005184  , 0.00535824],
       [0.00059049, 0.00097344, 0.00147456, 0.00210681, 0.00285156,
        0.00355216, 0.00423801, 0.00480249, 0.00519841, 0.00535824],
       [0.00061504, 0.00098596, 0.00151321, 0.00215296, 0.00288369,
        0.00357604, 0.00427716, 0.00481636, 0.00521284, 0.00538756],
       [0.00062001, 0.00101124, 0.00154449, 0.002209  , 0.00292681,
        0.00361201, 0.00430336, 0.00483025, 0.00524176, 0.00537289],
       [0.00065025, 0.00104329, 0.00157609, 0.00226576, 0.00298116,
        0.00366025, 0.00432964, 0.00484416, 0.00522729, 0.00537289],
       [0.00069169, 0.00109561, 0.00163216, 0.00231361, 0.00304704,
        0.00373321, 0.004356  , 0.00487204, 0.00529984, 0.00537289],
       [0.00073984, 0.001156  , 0.00168921, 0.00238144, 0.00310249,
        0.00379456, 0.00440896, 0.0049    , 0.00525625, 0.00535824],
       [0.00078961, 0.00121801, 0.0017724

In [193]:
r =z/np.cos(theta_rad)
r.shape

(72, 10)

In [177]:
x = -r * np.sin (theta_rad) * np.sin(phi_rad)
y = -r * np.sin(theta_rad) * np.cos(phi_rad)

In [180]:
plt.figure(figsize=(15,10))

plt.pcolormesh(x,y,squared_voltage,shading= 'auto')
plt.colorbar()

/tmp/ipykernel_3985/1947360733.py:3: UserWarning: The input coordinates to pcolormesh are interpreted as cell centers, but are not monotonically increasing or decreasing. This may lead to incorrectly calculated cell edges, in which case, please supply explicit cell edges to pcolormesh.
  plt.pcolormesh(x,y,squared_voltage,shading= 'auto')


In [187]:
plt.figure(figsize=(15,10))
w_z = w_0 * np.sqrt(1+(z/z_r))
#x= np.linspace(-w_z,w_z,1001)
#y= np.linspace(-w_z,w_z,1001)
#xv, yv = np.meshgrid(x,y)
roh = np.sqrt(x**2+y**2)
I = I_0  * np.exp(-0.8*roh**2/(w_z**2))
plt.pcolormesh(x,y,I,shading= 'auto')
plt.colorbar()

/tmp/ipykernel_3985/2015470089.py:8: UserWarning: The input coordinates to pcolormesh are interpreted as cell centers, but are not monotonically increasing or decreasing. This may lead to incorrectly calculated cell edges, in which case, please supply explicit cell edges to pcolormesh.
  plt.pcolormesh(x,y,I,shading= 'auto')


In [183]:
I.min()

4.6226419611216116e-06

In [185]:
I.max()/np.exp(2)

7.29126958554245e-04