In [176]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython import get_ipython

In [177]:
ipy = get_ipython()
if ipy is not None:
    ipy.run_line_magic('matplotlib', 'qt5')

## Gaussian Beam Intensity

$$ \large I(\rho , z) = I_0 \ (\frac{\omega_{0}}{\omega(z)}) ^2 \; \exp {(\frac{-2\rho^2}{\omega^{2}(z)})} $$ 

$$ \omega(z) = \omega_0 \ \large [1 + (\frac{z}{z_R})^2]^{\frac{1}{2}}  $$

$$ \large z_R = \frac{\pi \ \omega_0^2}{\lambda} $$

$$ \large \theta = \frac{\lambda}{\pi \ \omega_0} \ \ \ \ \ \ \ \ \ \ \ for \ z >> z_R$$

In [178]:
# measured values
z = 1
wl = 714.285 * 1e-6                                                # (m) wavelengththeta = 1.8 * (np.pi/180)
angle = 1.8 * (np.pi/180)                               # (radian) divergence angle of the beam     
w_0 = wl / (np.pi* angle)
z_r = (np.pi* w_0**2)/ wl

In [179]:
# measured values at specific plane (z)
I_0 = 0.00538756 
w_z = w_0 * np.sqrt(1+(z/z_r))

# Experimental data

In [180]:
names=['phi', 'theta', 'V']
df = pd.read_csv('data1.csv', header=None, delimiter = ';',names=names, index_col= False)
df['sq_V'] = df['V']**2

In [181]:
df.head(3)

phi  theta       V          sq_V
0  0.0   10.0  0.0002  4.000000e-08
1  0.0    9.8  0.0002  4.000000e-08
2  0.0    9.6  0.0003  9.000000e-08

In [182]:
data = df[df['theta']<2]           # choose the data within the range (0 to 1.8 degree) the half_divergence angle
data.head(3)

phi  theta       V      sq_V
41  0.0    1.8  0.0246  0.000605
42  0.0    1.6  0.0313  0.000980
43  0.0    1.4  0.0383  0.001467

In [189]:
# preparing the data theta, phi for the 2D plot
phi = np.arange(0,360,5)
theta = np.arange(0,2,0.2)
#theta = np.linspace (1.8,0, 10)
theta, phi = np.meshgrid(theta,phi)
# convert theta and phi to radian
theta_rad = theta * (np.pi/180)
phi_rad = phi * (np.pi/180)

In [190]:
theta

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8

In [191]:
phi

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   5,   5,   5,   5,   5,   5,   5,   5,   5],
       [ 10,  10,  10,  10,  10,  10,  10,  10,  10,  10],
       [ 15,  15,  15,  15,  15,  15,  15,  15,  15,  15],
       [ 20,  20,  20,  20,  20,  20,  20,  20,  20,  20],
       [ 25,  25,  25,  25,  25,  25,  25,  25,  25,  25],
       [ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30],
       [ 35,  35,  35,  35,  35,  35,  35,  35,  35,  35],
       [ 40,  40,  40,  40,  40,  40,  40,  40,  40,  40],
       [ 45,  45,  45,  45,  45,  45,  45,  45,  45,  45],
       [ 50,  50,  50,  50,  50,  50,  50,  50,  50,  50],
       [ 55,  55,  55,  55,  55,  55,  55,  55,  55,  55],
       [ 60,  60,  60,  60,  60,  60,  60,  60,  60,  60],
       [ 65,  65,  65,  65,  65,  65,  65,  65,  65,  65],
       [ 70,  70,  70,  70,  70,  70,  70,  70,  70,  70],
       [ 75,  75,  75,  75,  75,  75,  75,  75,  75,  75],
       [ 80,  80,  80,  80,  80,  80,  80,  80,  80,  80

In [192]:
# the measured sq_V
values= data.sq_V.values          
sq_voltage = values.reshape(72,10)
sq_voltage = np.flip(sq_voltage,1)         # flip the measured values
sq_voltage

array([[0.00535824, 0.005184  , 0.00478864, 0.004225  , 0.00354025,
        0.00284089, 0.00209764, 0.00146689, 0.00097969, 0.00060516],
       [0.00535824, 0.00519841, 0.00480249, 0.00423801, 0.00355216,
        0.00285156, 0.00210681, 0.00147456, 0.00097344, 0.00059049],
       [0.00538756, 0.00521284, 0.00481636, 0.00427716, 0.00357604,
        0.00288369, 0.00215296, 0.00151321, 0.00098596, 0.00061504],
       [0.00537289, 0.00524176, 0.00483025, 0.00430336, 0.00361201,
        0.00292681, 0.002209  , 0.00154449, 0.00101124, 0.00062001],
       [0.00537289, 0.00522729, 0.00484416, 0.00432964, 0.00366025,
        0.00298116, 0.00226576, 0.00157609, 0.00104329, 0.00065025],
       [0.00537289, 0.00529984, 0.00487204, 0.004356  , 0.00373321,
        0.00304704, 0.00231361, 0.00163216, 0.00109561, 0.00069169],
       [0.00535824, 0.00525625, 0.0049    , 0.00440896, 0.00379456,
        0.00310249, 0.00238144, 0.00168921, 0.001156  , 0.00073984],
       [0.00535824, 0.00524176, 0.0049140

In [193]:
# the distance from source to receiver
r = z/np.cos(theta_rad)
r.shape

(72, 10)

In [196]:
x = - r * np.sin (theta_rad) * np.sin(phi_rad)
y = - r * np.sin(theta_rad) * np.cos(phi_rad)

In [202]:
x.max()

0.03142626604335114

In [204]:
y.max()

0.03142626604335114

In [200]:
# the experimental data corresponding to beam_divergence (theta= 1.8)
plt.figure(figsize=(15,10))
plt.pcolormesh(x,y,sq_voltage, shading= 'auto')
plt.colorbar()

/tmp/ipykernel_19172/1611157749.py:3: UserWarning: The input coordinates to pcolormesh are interpreted as cell centers, but are not monotonically increasing or decreasing. This may lead to incorrectly calculated cell edges, in which case, please supply explicit cell edges to pcolormesh.
  plt.pcolormesh(x,y,sq_voltage, shading= 'auto')


In [201]:
#theory

plt.figure(figsize=(15,10))
I =  I_0 * np.exp((-2*roh**2)/w_z**2)
plt.pcolormesh(x,y, I, shading= 'auto')
plt.colorbar()

NameError: name 'roh' is not defined